#!/usr/bin/bash
set -e

### NOTE: configure ###
[[ -d /opt/umu ]] || sudo mkdir -p          /opt/umu
[[ -w /opt/umu ]] || sudo chown retro:retro /opt/umu

if [[ $# -eq 0 ]]
then
    exit
fi

n=$1
shift


### NOTE: install ###
export WINEPREFIX=/opt/umu/.install-prefix

mkdir -p   /opt/umu/"$n" "$WINEPREFIX"/dosdevices
ln    -sfT /opt/umu/"$n" "$WINEPREFIX"/dosdevices/d:

if [[ $# -ge 1 ]]
then
    ur "$@"
fi


cd /opt/umu/"$n"
sel() {
    readarray -t O < $1

    if [[ ${#O[@]} -eq 1 ]]
    then
        echo "$O"
    else
        select o in "${O[@]}"
        do
            echo "$o"
            break
        done
    fi
}

if ! [[ -e exe ]]
then
    lnk=$(sel <(find $WINEPREFIX/drive_c/users/*/Desktop -type f))
    exe=$(sel <(strings "$lnk" | grep -o "D:.*exe"))

    if [[ -n $exe ]]
    then
        exe=$(ur winepath -u "$exe")
    else
        read -p "exe: " exe
    fi

    ln -sr "$exe" exe
fi

if ! [[ -f icon.png ]]
then
    icoextract exe icon.ico

    mkdir -p icons
    magick icon.ico icons/icon.png

    mv "$(du -b icons/* | sort -nr | head -1 | cut -f2)" icon.png
    rm -rf icon.ico icons
fi
